# Generated by Django 4.1.3 on 2022-12-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0006_userrelationship_unique_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrelationship',
            name='unique_follow',
        ),
        migrations.AddConstraint(
            model_name='userrelationship',
            constraint=models.UniqueConstraint(fields=('follower_id', 'following_id'), name='unique_follow'),
        ),
    ]
